// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJyNa-6AV_TsJCvwtC_IIsRewVpOZJKE',
    appId: '1:719880802530:web:f121bc455f42409f164ebb',
    messagingSenderId: '719880802530',
    projectId: 'assignder-e50c0',
    authDomain: 'assignder-e50c0.firebaseapp.com',
    storageBucket: 'assignder-e50c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBALk_04jWu3I9MFFbK9gXc7UTQH24HKI',
    appId: '1:719880802530:android:3c5f33326819d65a164ebb',
    messagingSenderId: '719880802530',
    projectId: 'assignder-e50c0',
    storageBucket: 'assignder-e50c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHIfTk9B0qWk0Sl0AEdX-B8auMNVzcGlE',
    appId: '1:719880802530:ios:fe4ba062c856788c164ebb',
    messagingSenderId: '719880802530',
    projectId: 'assignder-e50c0',
    storageBucket: 'assignder-e50c0.firebasestorage.app',
    iosBundleId: 'com.example.assignder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHIfTk9B0qWk0Sl0AEdX-B8auMNVzcGlE',
    appId: '1:719880802530:ios:fe4ba062c856788c164ebb',
    messagingSenderId: '719880802530',
    projectId: 'assignder-e50c0',
    storageBucket: 'assignder-e50c0.firebasestorage.app',
    iosBundleId: 'com.example.assignder',
  );
}
